version: "3.9"

services:
  promobot:
    container_name: promobot
    restart: always
    ports:
      - "8888:4444"
    volumes:
      - ./db_files:/bot/db_files
      - ./вопросы-ответы.txt:/bot/вопросы-ответы.txt
    build: .
    command: ['python', 'main.py', 'fill_db']

